#!/usr/bin/env python
"""Regenerate the documentation pages that are derived from code.

    uv run python tools/gen_docs.py          # write docs/checks.md and docs/defects.md
    uv run python tools/gen_docs.py --check  # fail if they are out of date (CI)

The catalogue of checks and the catalogue of defects each live in one place in
the code. The docs are rendered from there so the two can never disagree.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "demo/src"))

from acme_mail_mcp.defects import REGISTRY as DEFECTS  # noqa: E402
from mcpqa.checks import all_checks  # noqa: E402

HEADER = "<!-- generated by tools/gen_docs.py; do not edit by hand -->\n"
LAYERS = {
    1: "Protocol and transport",
    2: "Tool contracts and annotations",
    3: "Authorization and isolation",
    4: "Upstream behaviour",
    5: "Agent behaviour",
}


def checks_page() -> str:
    lines = [
        HEADER,
        "# The check catalogue",
        "",
        "Every check the kit runs against a server, with the sentence of the specification it",
        "enforces. Severity follows the keyword in that sentence — MUST is an error, SHOULD a",
        "warning, anything else a note — and the few checks that are stricter than their keyword",
        "say why. `tests/unit/test_spec_quotes.py` verifies every quote against the specification",
        "text, and `tests/unit/test_checks_fire.py` proves every check fails against a server that",
        "breaks its rule.",
        "",
    ]
    for layer in (1, 2):
        lines += [f"## Layer {layer} — {LAYERS[layer]}", ""]
        for check in (c for c in all_checks() if c.layer == layer):
            scope = f"{' + '.join(check.eras)} · {' + '.join(check.transports)}"
            needs = f" · needs: {', '.join(check.needs)}" if check.needs else ""
            lines += [f"### {check.id} · {check.title}", "", f"**{check.severity}** · {scope}{needs}", ""]
            if check.ref.quote:
                source = f"{check.ref.version} · {check.ref.section or 'overview'}"
                lines += [f"> {check.ref.quote}", ">", f"> — [{source}]({check.ref.url})", ""]
            else:
                lines += [f"No normative sentence: engineering practice ([context]({check.ref.url})).", ""]
            if check.escalation:
                lines += [f"*Stricter than its keyword because:* {check.escalation}", ""]
    lines += [
        "## Layers 3 and 4",
        "",
        "Authorization, tenancy, credential handling and upstream behaviour depend on the connector's",
        "domain, so they are scenario tests rather than portable checks: see `tests/layer3_auth/` and",
        "`tests/layer4_upstream/`. The portable parts — HTTP authorization (H-008 to H-010) and the",
        "credential leak scan in `mcpqa.leaks` — are available to any suite.",
        "",
    ]
    return "\n".join(lines)


def defects_page() -> str:
    lines = [
        HEADER,
        "# The seeded defect catalogue",
        "",
        "Each defect is a realistic way to build the demo connector wrong, introduced by swapping one",
        "part of its composition (see `demo/src/acme_mail_mcp/defects.py`). Start the connector with",
        "`ACME_MCP_DEFECTS=<id>` to reproduce any of them. Which layer actually catches each one is",
        "measured, not asserted: see [the defect matrix](defect-matrix.md).",
        "",
        "| Defect | Expected layer | What breaks | Where this happens for real |",
        "| --- | :-: | --- | --- |",
    ]
    for defect in DEFECTS.values():
        lines.append(f"| `{defect.id}` | {defect.expected_layer} | {defect.breaks} | {defect.real_world} |")
    lines += [
        "",
        "## One defect that is not here",
        "",
        "A stray `print()` that corrupts the stdio stream is the most common stdio bug in the wild, and",
        "it cannot be seeded into this connector: while the Python SDK's `stdio_server()` is serving, it",
        "points file descriptor 1 at stderr and keeps the protocol stream on a private descriptor, so",
        "handler output never reaches the wire. The check for it (P-014) is still in the kit — servers",
        "built on other SDKs, or on none, are not protected — and the fixture server proves it fires.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    pages = {ROOT / "docs/checks.md": checks_page(), ROOT / "docs/defects.md": defects_page()}
    stale = [path for path, content in pages.items() if not path.exists() or path.read_text() != content]
    if args.check:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)} (run `make docs`)")
        return 1 if stale else 0
    for path, content in pages.items():
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
